import { FeatureFlag, BlogPost } from '@/lib/admin-types';

export const MOCK_FEATURES: FeatureFlag[] = [
  {
    id: 'f1',
    key: 'carrier_pulse_enabled',
    label: 'CarrierPulse Service',
    description: 'Enable the AI-powered telecom market intelligence service across the platform.',
    enabled: true,
    scope: 'service',
    service: 'carrier-pulse',
    updatedAt: '2026-03-08T14:22:00Z',
    updatedBy: 'Alex Chen',
  },
  {
    id: 'f2',
    key: 'ai_support_enabled',
    label: 'AI Support Service',
    description: 'Enable the AI assistant for telecom operations and insight.',
    enabled: false,
    scope: 'service',
    service: 'ai-support',
    updatedAt: '2026-03-01T10:00:00Z',
    updatedBy: 'Alex Chen',
  },
  {
    id: 'f3',
    key: 'usage_engine_enabled',
    label: 'Usage Engine Service',
    description: 'Enable telecom usage processing, ingestion, normalization, and anomaly detection.',
    enabled: false,
    scope: 'service',
    service: 'usage-engine',
    updatedAt: '2026-02-20T09:00:00Z',
    updatedBy: 'Alex Chen',
  },
  {
    id: 'f4',
    key: 'analytics_engine_enabled',
    label: 'Analytics Engine Service',
    description: 'Enable decision-grade metrics, KPI engine, dashboards, and reports.',
    enabled: false,
    scope: 'service',
    service: 'analytics',
    updatedAt: '2026-02-20T09:00:00Z',
    updatedBy: 'Alex Chen',
  },
  {
    id: 'f5',
    key: 'multi_tenant_mode',
    label: 'Multi-Tenant Mode',
    description: 'Allow users to switch between multiple tenants. Disable for single-org deployments.',
    enabled: true,
    scope: 'platform',
    updatedAt: '2026-01-15T08:30:00Z',
    updatedBy: 'Alex Chen',
  },
  {
    id: 'f6',
    key: 'global_search',
    label: 'Global Search',
    description: 'Enable the platform-wide search across all services, tenants, and data.',
    enabled: true,
    scope: 'platform',
    updatedAt: '2026-03-05T16:10:00Z',
    updatedBy: 'Alex Chen',
  },
  {
    id: 'f7',
    key: 'email_notifications',
    label: 'Email Notifications',
    description: 'Send email notifications for alerts, reports, and intelligence briefs.',
    enabled: true,
    scope: 'platform',
    updatedAt: '2026-03-07T11:45:00Z',
    updatedBy: 'Alex Chen',
  },
  {
    id: 'f8',
    key: 'brand_onboarding_ai',
    label: 'AI Brand Onboarding',
    description: 'Use AI to research and generate brand profiles during onboarding.',
    enabled: true,
    scope: 'service',
    service: 'carrier-pulse',
    updatedAt: '2026-03-08T14:22:00Z',
    updatedBy: 'Alex Chen',
  },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: 'bp1',
    title: 'Introducing CarrierPulse: AI-Powered Telecom Intelligence',
    slug: 'introducing-carrier-pulse',
    excerpt: 'How our AI agent monitors the telecom landscape and delivers actionable intelligence to MVNOs.',
    body: '# Introducing CarrierPulse\n\nCarrierPulse is our flagship AI-powered intelligence service designed specifically for MVNOs and telecom operators.\n\n## What it does\n\nCarrierPulse continuously monitors the telecom landscape, researching carriers, competitors, and market trends to deliver actionable intelligence.\n\n## Key Features\n\n- **Digital Twin Profiles** — AI-generated company profiles that power intelligent monitoring\n- **Automated Research** — Weekly search cycles across customizable categories\n- **Smart Briefs** — AI-curated intelligence briefs delivered via email\n- **Trend Detection** — Pattern recognition across findings over time\n\nStay tuned for more updates as we continue to enhance the platform.',
    status: 'published',
    author: 'Alex Chen',
    tags: ['product', 'ai', 'carrier-pulse'],
    publishedAt: '2026-02-15T10:00:00Z',
    createdAt: '2026-02-14T16:30:00Z',
    updatedAt: '2026-02-15T10:00:00Z',
  },
  {
    id: 'bp2',
    title: 'Platform Security: Our Approach to Data Protection',
    slug: 'platform-security-approach',
    excerpt: 'An overview of the security measures and practices we implement to protect your data.',
    body: '# Platform Security\n\nSecurity is foundational to everything we build at IRIE Wireless.\n\n## Authentication & Authorization\n\n- Role-based access control (RBAC) with 7 granular roles\n- JWT-based authentication with configurable expiry\n- Multi-tenant isolation\n\n## Data Protection\n\n- All data encrypted at rest and in transit\n- Configurable data retention policies per tenant\n- Audit logging for all administrative actions\n\nWe are committed to maintaining the highest security standards.',
    status: 'published',
    author: 'Alex Chen',
    tags: ['security', 'platform'],
    publishedAt: '2026-03-01T09:00:00Z',
    createdAt: '2026-02-28T14:00:00Z',
    updatedAt: '2026-03-01T09:00:00Z',
  },
  {
    id: 'bp3',
    title: 'Usage Engine Preview: What to Expect',
    slug: 'usage-engine-preview',
    excerpt: 'A sneak peek at the upcoming Usage Engine — real-time telecom usage processing and visibility.',
    body: '# Usage Engine Preview\n\nWe are excited to share a preview of the upcoming Usage Engine service.\n\n## Core Capabilities\n\n- Real-time usage ingestion and normalization\n- Anomaly detection and alerting\n- Usage forecasting and trend analysis\n- Multi-carrier aggregation\n\n## Timeline\n\nThe Usage Engine is currently in development and will be available soon.',
    status: 'draft',
    author: 'Alex Chen',
    tags: ['product', 'usage-engine', 'preview'],
    publishedAt: null,
    createdAt: '2026-03-08T11:00:00Z',
    updatedAt: '2026-03-08T15:30:00Z',
  },
];
