import { AuditLogEntry } from '../types';

export const MOCK_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: 'audit_1',
    tenantId: 'tenant_bolt',
    userId: 'user_alex',
    userName: 'Alex Chen',
    action: 'user.login',
    resource: 'session',
    details: 'Logged in via SSO',
    timestamp: '2026-03-07T08:30:00Z',
    ipAddress: '192.168.1.42',
  },
  {
    id: 'audit_2',
    tenantId: 'tenant_bolt',
    userId: 'user_sarah',
    userName: 'Sarah Mitchell',
    action: 'tenant.config_update',
    resource: 'tenant/tenant_bolt',
    details: 'Updated data retention policy from 180 to 365 days',
    timestamp: '2026-03-07T07:15:00Z',
    ipAddress: '10.0.0.88',
  },
  {
    id: 'audit_3',
    tenantId: 'tenant_verdant',
    userId: 'user_james',
    userName: 'James Rivera',
    action: 'report.export',
    resource: 'reports/monthly-feb-2026',
    details: 'Exported monthly analytics report as PDF',
    timestamp: '2026-03-06T16:45:00Z',
    ipAddress: '172.16.0.12',
  },
  {
    id: 'audit_4',
    tenantId: 'tenant_bolt',
    userId: 'user_alex',
    userName: 'Alex Chen',
    action: 'user.role_change',
    resource: 'users/user_priya',
    details: 'Changed role from viewer to operator',
    timestamp: '2026-03-06T14:20:00Z',
    ipAddress: '192.168.1.42',
  },
  {
    id: 'audit_5',
    tenantId: 'tenant_bolt',
    userId: 'user_priya',
    userName: 'Priya Patel',
    action: 'alert.dismiss',
    resource: 'alerts/alert_usage_spike_42',
    details: 'Dismissed usage spike alert after investigation',
    timestamp: '2026-03-06T12:30:00Z',
    ipAddress: '10.0.0.91',
  },
  {
    id: 'audit_6',
    tenantId: 'tenant_nexgen',
    userId: 'user_alex',
    userName: 'Alex Chen',
    action: 'service.enable',
    resource: 'services/analytics',
    details: 'Enabled Analytics Engine for NexGen Connect',
    timestamp: '2026-03-06T10:00:00Z',
    ipAddress: '192.168.1.42',
  },
  {
    id: 'audit_7',
    tenantId: 'tenant_verdant',
    userId: 'user_james',
    userName: 'James Rivera',
    action: 'integration.update',
    resource: 'integrations/tmo-api',
    details: 'Updated T-Mobile API credentials',
    timestamp: '2026-03-05T18:00:00Z',
    ipAddress: '172.16.0.12',
  },
  {
    id: 'audit_8',
    tenantId: 'tenant_bolt',
    userId: 'user_sarah',
    userName: 'Sarah Mitchell',
    action: 'user.invite',
    resource: 'users/new_invite',
    details: 'Invited derek.wong@boltmobile.com as analyst',
    timestamp: '2026-03-05T15:30:00Z',
    ipAddress: '10.0.0.88',
  },
  {
    id: 'audit_9',
    tenantId: 'tenant_bolt',
    userId: 'user_alex',
    userName: 'Alex Chen',
    action: 'tenant.create',
    resource: 'tenants/tenant_nexgen',
    details: 'Created new tenant: NexGen Connect (trial)',
    timestamp: '2025-01-10T09:00:00Z',
    ipAddress: '192.168.1.42',
  },
  {
    id: 'audit_10',
    tenantId: 'tenant_bolt',
    userId: 'user_alex',
    userName: 'Alex Chen',
    action: 'data.export',
    resource: 'exports/subscriber-data-bolt',
    details: 'Exported subscriber data CSV (89,241 records)',
    timestamp: '2026-03-04T11:15:00Z',
    ipAddress: '192.168.1.42',
  },
];
