import { PlatformNotification } from '../types';

export const MOCK_NOTIFICATIONS: PlatformNotification[] = [
  {
    id: 'notif_1',
    tenantId: 'tenant_bolt',
    type: 'intelligence_brief',
    severity: 'info',
    title: 'Weekly Intelligence Brief Ready',
    description: 'CarrierPulse has generated the weekly brief for Bolt Mobile with 14 new findings.',
    timestamp: '2026-03-07T08:00:00Z',
    read: false,
    deepLink: '/platform/services/carrier-pulse',
    service: 'CarrierPulse',
  },
  {
    id: 'notif_2',
    tenantId: 'tenant_bolt',
    type: 'usage_spike',
    severity: 'warning',
    title: 'Unusual Usage Spike Detected',
    description: 'Data usage for Bolt Mobile spiked 340% in the US-East region over the last 2 hours.',
    timestamp: '2026-03-07T07:45:00Z',
    read: false,
    deepLink: '/platform/services/usage-engine',
    service: 'Usage Engine',
  },
  {
    id: 'notif_3',
    tenantId: 'tenant_verdant',
    type: 'carrier_outage',
    severity: 'critical',
    title: 'Carrier Outage: T-Mobile US-West',
    description: 'T-Mobile reporting service degradation in the US-West region affecting Verdant Wireless subscribers.',
    timestamp: '2026-03-07T06:30:00Z',
    read: false,
    service: 'Platform',
  },
  {
    id: 'notif_4',
    tenantId: 'tenant_bolt',
    type: 'ai_recommendation',
    severity: 'info',
    title: 'AI Recommendation: Plan Optimization',
    description: 'AI Support suggests 12% of Bolt Mobile subscribers would benefit from plan tier migration.',
    timestamp: '2026-03-06T22:15:00Z',
    read: true,
    deepLink: '/platform/services/ai-support',
    service: 'AI Support',
  },
  {
    id: 'notif_5',
    tenantId: 'tenant_nexgen',
    type: 'action_assigned',
    severity: 'info',
    title: 'Action Item Assigned',
    description: 'Review competitive pricing analysis for NexGen Connect market positioning.',
    timestamp: '2026-03-06T18:00:00Z',
    read: true,
    deepLink: '/platform/services/carrier-pulse',
    service: 'CarrierPulse',
  },
  {
    id: 'notif_6',
    tenantId: 'tenant_bolt',
    type: 'report_ready',
    severity: 'success',
    title: 'Monthly Analytics Report Ready',
    description: 'February 2026 analytics report for Bolt Mobile is ready for review and export.',
    timestamp: '2026-03-06T10:00:00Z',
    read: true,
    deepLink: '/platform/reports',
    service: 'Analytics Engine',
  },
  {
    id: 'notif_7',
    tenantId: 'tenant_verdant',
    type: 'trend_detected',
    severity: 'info',
    title: 'New Trend Signal: 5G Migration',
    description: 'CarrierPulse detected an accelerating trend in 5G migration among Verdant Wireless competitors.',
    timestamp: '2026-03-05T14:30:00Z',
    read: true,
    deepLink: '/platform/services/carrier-pulse',
    service: 'CarrierPulse',
  },
  {
    id: 'notif_8',
    tenantId: 'tenant_bolt',
    type: 'billing_anomaly',
    severity: 'warning',
    title: 'Billing Anomaly Detected',
    description: 'Roaming charges for 23 Bolt Mobile devices exceed expected thresholds by 180%.',
    timestamp: '2026-03-05T11:20:00Z',
    read: true,
    service: 'Usage Engine',
  },
];
