"""Async email delivery for intelligence briefs."""

from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import aiosmtplib

from config import settings


async def send_brief_email(brief_markdown: str, brand_name: str = "USA Mobile"):
    """Send the weekly brief via email."""
    if not all([settings.email_to, settings.email_from, settings.smtp_password]):
        return

    today = datetime.now().strftime("%B %d, %Y")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"{brand_name} Weekly Intel Brief - {today}"
    msg["From"] = settings.email_from
    msg["To"] = settings.email_to

    # Plain text
    msg.attach(MIMEText(brief_markdown, "plain"))

    # HTML version
    html_brief = brief_markdown.replace("\n\n", "</p><p>").replace("\n", "<br>")
    html_content = f"""
    <html>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                 max-width: 800px; margin: 0 auto; padding: 20px; color: #1a1a1a;">
        <div style="border-bottom: 3px solid #0066cc; padding-bottom: 15px; margin-bottom: 25px;">
            <h1 style="margin: 0; color: #0066cc;">{brand_name}</h1>
            <h2 style="margin: 5px 0 0 0; color: #444; font-weight: normal;">
                Weekly Telecom News Brief - {today}
            </h2>
            <p style="color: #888; margin: 5px 0 0 0;">
                Prepared by CarrierPulse
            </p>
        </div>
        <p>{html_brief}</p>
        <div style="border-top: 1px solid #ddd; margin-top: 30px; padding-top: 15px; color: #888;">
            <small>Generated by CarrierPulse — AI Telecom News Agent</small>
        </div>
    </body>
    </html>
    """
    msg.attach(MIMEText(html_content, "html"))

    await aiosmtplib.send(
        msg,
        hostname=settings.smtp_server,
        port=settings.smtp_port,
        username=settings.email_from,
        password=settings.smtp_password,
        start_tls=True,
    )
